
MethodLength:
  Max: 200

LineLength:
  Max: 160

AbcSize:
  Max: 100

FileName:
  Enabled: false

PerceivedComplexity:
  Enabled: false

CyclomaticComplexity:
  Enabled: false

ClassLength:
  Enabled: false

IfUnlessModifier:
  Enabled: false

RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/HashAlignment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/RedundantCondition:
  Enabled: false

Style/GuardClause:
  Enabled: false
